spring:
  sql:
    init:
      mode: always

  docker:
    compose:
      file: classpath:/compose.yaml

  security:
    oauth2:
      client:
        registration:
          dex:
            client-name: Dex IDP
            client-id: base-client
            client-secret: base-secret
            scope:
              - openid
              - email
              - profile
        provider:
          dex:
            issuer-uri: http://localhost:5556


#logging:
#  level:
#    org.springframework.security: TRACE
server:
  servlet:
    session:
      persistent: true
  port: 8081
  address: 127.0.0.1