spring:
  sql:
    init:
      mode: always
  docker:
    compose:
      file: compose.yaml
#logging:
#  level:
#    org.springframework.security: TRACE
server:
  servlet:
    session:
      persistent: true
  port: 8081
  address: 127.0.0.1