spring:
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false
#logging:
#  level:
#    org.springframework.security: TRACE
server:
  servlet:
    session:
      persistent: true
  port: 8080
  address: 127.0.0.1
